version: 2.1

jobs:

  build-test-docker:
    docker:
      - image: cimg/openjdk:21.0

    steps:
      - checkout

      # =========================
      # 1. Build API Gateway
      # =========================
      - run:
          name: Build API Gateway
          command: |
            cd APIGateway
            mvn clean package -DskipTests

      # =========================
      # 2. Build Category Service
      # =========================
      - run:
          name: Build Category Service
          command: |
            cd Category-service
            mvn clean package -DskipTests

      # =========================
      # 3. Build Config Server
      # =========================
      - run:
          name: Build Config Server
          command: |
            cd Config-server
            mvn clean package -DskipTests

      # =========================
      # 4. Build Eureka Server
      # =========================
      - run:
          name: Build Eureka Server
          command: |
            cd Eureka
            mvn clean package -DskipTests

      # =========================
      # 5. Build Product Service
      # =========================
      - run:
          name: Build Product Service
          command: |
            cd Product-service
            mvn clean package -DskipTests

      # =========================
      # Docker
      # =========================
      - setup_remote_docker

      # =========================
      # Login Docker Hub
      # =========================
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login \
              -u "$DOCKERHUB_USERNAME" \
              --password-stdin

      # =========================
      # Build Docker Images
      # =========================
      - run:
          name: Build Docker Images
          command: |
            docker build \
              -t $DOCKERHUB_USERNAME/api-gateway:$CIRCLE_SHA1 \
              api-gateway

            docker build \
              -t $DOCKERHUB_USERNAME/category-service:$CIRCLE_SHA1 \
              category-service

            docker build \
              -t $DOCKERHUB_USERNAME/config-server:$CIRCLE_SHA1 \
              config-server

            docker build \
              -t $DOCKERHUB_USERNAME/eureka-server:$CIRCLE_SHA1 \
              eureka-server

            docker build \
              -t $DOCKERHUB_USERNAME/product-service:$CIRCLE_SHA1 \
              product-service

      # =========================
      # Push Docker Images
      # =========================
      - run:
          name: Push Docker Images
          command: |
            docker push \
              $DOCKERHUB_USERNAME/api-gateway:$CIRCLE_SHA1

            docker push \
              $DOCKERHUB_USERNAME/category-service:$CIRCLE_SHA1

            docker push \
              $DOCKERHUB_USERNAME/config-server:$CIRCLE_SHA1

            docker push \
              $DOCKERHUB_USERNAME/eureka-server:$CIRCLE_SHA1

            docker push \
              $DOCKERHUB_USERNAME/product-service:$CIRCLE_SHA1


workflows:

  build-deploy:
    jobs:
      - build-test-docker