spring.application.name=Config-server

server.port=8888

# Git Repository (CONFIG REPO)
spring.cloud.config.server.git.uri=https://github.com/Ellin2024/config-repo-v1.git

# Clone repo on startup (recommended)
spring.cloud.config.server.git.clone-on-start=true

# Optional: if repo is private (use token)
# spring.cloud.config.server.git.username=your-username
# spring.cloud.config.server.git.password=your-token

# Optional: default branch
spring.cloud.config.server.git.default-label=main

# Logging (optional but useful for debugging)
logging.level.org.springframework.cloud.config=DEBUG